# General Jekyll options https://jekyllrb.com/docs/configuration/
exclude:
  - README.md
plugins:
  - jekyll-remote-theme

# Theme and theme options
remote_theme: carlosperate/jekyll-theme-documentation

# Site settings
title: "BBC micro:bit Bird Activity" 
description: "Play with micro:bit and join the flock!"
owner_name: "Micro:bit Educational Foundation"
owner_url: "https://microbit-carlos.github.io/microbit-bird-activity/"
custom_css: "assets/css/custom_style.css"
permalink: pretty
nav:
  - Getting Started:
    - Introduction: ''
  - Bird Making:
    - Bird Pipe Cleaners: birdcraft
  - It's alive:
    - Coding Activity: activity
    - Submit Your SoundEffects: submitse
    - Advanced Coding Steps : activityadvanced
  - More info:
    - Python Editor: 'editor'
    - MicroPython: 'micropython'
